server:
  port: 8085
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saloon_service_db
    username: postgres
    password: CG-46331722
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    validation:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        validator: DEBUG

  #h2:
    #console:
    #  enabled: true
